---
name: On-PR to main

on:
  pull_request:
    branches: ["main"]

permissions:
  pull-requests: write
  contents: write
  actions: read
  security-events: write

jobs:
  dependabot:
    uses: ./.github/workflows/99-auto-merge.yml

  labeler:
    if: github.event.pull_request.head.repo.owner.login == 'db-ux-design-system'
    uses: ./.github/workflows/99-labeler.yml
